package ngen.backend

import ngen.algebra.NttDomain
import ngen.algebra.Modulus
import ngen.arithmetic.BarrettField
import ngen.rtl.*

object GraphSystemVerilog:
  private def declaration(format: ValueFormat): String =
    val signed = if format.signed then "signed " else ""
    if format.width == 1 then signed else s"$signed[${format.width - 1}:0] "

  def emit(graph: TimedGraph, domain: NttDomain, top: String = "main"): String =
    emit(graph,domain.modulus,domain.size,top)

  def emit(graph: TimedGraph, field: Modulus, size: Int, top: String): String =
    require(top.matches("[A-Za-z_][A-Za-z0-9_$]*"), s"invalid SystemVerilog module name: $top")
    val barrett = BarrettField(field)
    val width = field.bitWidth
    val inputs = graph.nodes.collect { case Node(signal, InputOperator(port, format), _) => (signal, port, format) }
    require(inputs.map(_._2).sorted == Vector.tabulate(size)(i => s"i$i").sorted, "generic NTT graph must expose i0..iN-1")
    require(graph.outputs.size == size)

    val nodeById = graph.nodes.map(node => node.signal.id -> node).toMap
    def reference(signal: Signal): String = nodeById(signal.id).operator match
      case InputOperator(port, _) => port
      case _ => s"s${signal.id}"

    def expression(node: Node): String = node.operator match
      case _: Delay => reference(node.inputs.head)
      case _: ModularAdd => s"mod_add(${reference(node.inputs(0))}, ${reference(node.inputs(1))})"
      case _: ModularSubtract => s"mod_sub(${reference(node.inputs(0))}, ${reference(node.inputs(1))})"
      case op: BarrettMultiplyConstant =>
        s"barrett_mul(${reference(node.inputs.head)}, ${width}'d${field.normalize(op.constant)})"
      case unsupported => throw new IllegalArgumentException(s"generic SystemVerilog backend does not support ${unsupported.name}")

    val ports =
      Vector("input clock", "input reset", "input next") ++
        inputs.sortBy(_._2.drop(1).toInt).map((_, port, format) => s"input ${declaration(format)}$port") ++
        Vector("output next_out") ++
        graph.outputs.indices.map(i => s"output ${declaration(graph.outputs(i).format)}o$i")

    val declarations = graph.nodes.flatMap { node =>
      node.operator match
        case _: InputOperator => Vector.empty
        case operator if operator.latency == 0 =>
          Vector(s"  wire ${declaration(node.signal.format)}s${node.signal.id};")
        case operator =>
          Vector(
            s"  reg ${declaration(node.signal.format)}s${node.signal.id}_pipe [0:${operator.latency - 1}];",
            s"  wire ${declaration(node.signal.format)}s${node.signal.id} = s${node.signal.id}_pipe[${operator.latency - 1}];"
          )
    }

    val combinational = graph.nodes.flatMap { node =>
      node.operator match
        case _: InputOperator => Vector.empty
        case operator if operator.latency == 0 => Vector(s"  assign s${node.signal.id} = ${expression(node)};")
        case _ => Vector.empty
    }

    val resetLines = graph.nodes.flatMap { node =>
      node.operator match
        case operator if !operator.isInstanceOf[InputOperator] && operator.latency > 0 =>
          Vector.tabulate(operator.latency)(index => s"      s${node.signal.id}_pipe[$index] <= '0;")
        case _ => Vector.empty
    } ++ Vector.tabulate(graph.latency)(index => s"      next_pipe[$index] <= 1'b0;")

    val clockLines = graph.nodes.flatMap { node =>
      node.operator match
        case _: InputOperator => Vector.empty
        case operator if operator.latency > 0 =>
          Vector(s"      s${node.signal.id}_pipe[0] <= ${expression(node)};") ++
            Vector.tabulate(operator.latency - 1)(index => s"      s${node.signal.id}_pipe[${index + 1}] <= s${node.signal.id}_pipe[$index];")
        case _ => Vector.empty
    } ++
      (if graph.latency == 0 then Vector.empty
       else Vector("      next_pipe[0] <= next;") ++ Vector.tabulate(graph.latency - 1)(index => s"      next_pipe[${index + 1}] <= next_pipe[$index];"))

    val outputAssignments = graph.outputs.zipWithIndex.map((signal, index) => s"  assign o$index = ${reference(signal)};")
    val nextDeclaration = if graph.latency == 0 then Vector.empty else Vector(s"  reg next_pipe [0:${graph.latency - 1}];")
    val nextAssignment = if graph.latency == 0 then "  assign next_out = next;" else s"  assign next_out = next_pipe[${graph.latency - 1}];"

    s"""// Generated by NGen's canonical timed RTL graph backend.
       |/* verilator lint_off DECLFILENAME */
       |module $top(
       |${ports.map("  " + _).mkString(",\n")}
       |);
       |  localparam [${width - 1}:0] MODULUS = ${width}'d${field.q};
       |  localparam [${width}:0] MODULUS_EXT = ${width + 1}'d${field.q};
       |  localparam signed [${3 * width}:0] MODULUS_REMAINDER = ${3 * width + 1}'sd${field.q};
       |  localparam [${2 * width - 1}:0] BARRETT_MU = ${2 * width}'d${barrett.mu};
       |
       |  /* verilator lint_off UNUSEDSIGNAL */
       |  function automatic [${width - 1}:0] mod_add(input [${width - 1}:0] a, input [${width - 1}:0] b);
       |    reg [$width:0] sum;
       |    reg [$width:0] reduced;
       |    begin
       |      sum = {1'b0, a} + {1'b0, b};
       |      if (sum >= MODULUS_EXT) reduced = sum - MODULUS_EXT;
       |      else reduced = sum;
       |      mod_add = reduced[${width - 1}:0];
       |    end
       |  endfunction
       |
       |  function automatic [${width - 1}:0] mod_sub(input [${width - 1}:0] a, input [${width - 1}:0] b);
       |    reg [${width}:0] difference;
       |    begin
       |      if (a >= b) difference = {1'b0, a} - {1'b0, b};
       |      else difference = {1'b0, a} + MODULUS_EXT - {1'b0, b};
       |      mod_sub = difference[${width - 1}:0];
       |    end
       |  endfunction
       |
       |  function automatic [${width - 1}:0] barrett_mul(input [${width - 1}:0] a, input [${width - 1}:0] b);
       |    reg [${2 * width - 1}:0] product;
       |    reg [${4 * width - 1}:0] scaled;
       |    reg [${2 * width - 1}:0] quotient;
       |    reg [${3 * width - 1}:0] quotient_product;
       |    reg signed [${3 * width}:0] remainder;
       |    begin
       |      product = {{$width{1'b0}}, a} * {{$width{1'b0}}, b};
       |      scaled = {{${2 * width}{1'b0}}, product} * {{${2 * width}{1'b0}}, BARRETT_MU};
       |      quotient = scaled[${4 * width - 1}:${2 * width}];
       |      quotient_product = {{$width{1'b0}}, quotient} * {{${2 * width}{1'b0}}, MODULUS};
       |      remainder = $$signed({${width + 1}'d0, product}) - $$signed({1'b0, quotient_product});
       |      if (remainder < 0) remainder = remainder + MODULUS_REMAINDER;
       |      if (remainder >= MODULUS_REMAINDER) remainder = remainder - MODULUS_REMAINDER;
       |      if (remainder >= MODULUS_REMAINDER) remainder = remainder - MODULUS_REMAINDER;
       |      barrett_mul = remainder[${width - 1}:0];
       |    end
       |  endfunction
       |  /* verilator lint_on UNUSEDSIGNAL */
       |
       |${(declarations ++ nextDeclaration).mkString("\n")}
       |
       |${combinational.mkString("\n")}
       |${outputAssignments.mkString("\n")}
       |$nextAssignment
       |
       |  always @(posedge clock) begin
       |    if (reset) begin
       |${resetLines.mkString("\n")}
       |    end else begin
       |${clockLines.mkString("\n")}
       |    end
       |  end
       |endmodule
       |/* verilator lint_on DECLFILENAME */
       |""".stripMargin
