package ngen.backend

import ngen.algebra.Domains
import ngen.transform.KyberNtt

object KyberSystemVerilog:
  private val domain = Domains.Kyber256
  private val zetas = KyberNtt.zetas(domain).map(_.toInt)
  private def lines(values: Seq[String], spaces: Int): String = values.map(" " * spaces + _).mkString("\n")

  private def forwardBody: Vector[String] =
    var constantIndex = 1
    var result = Vector.empty[String]
    var length = 128
    while length >= 2 do
      var start = 0
      while start < 256 do
        val zeta = zetas(constantIndex)
        constantIndex += 1
        result ++= Vector(
          s"for (j = $start; j < ${start + length}; j = j + 1) begin",
          s"  butterfly_product = kyber_mul(work[j + $length], 12'd$zeta);",
          "  butterfly_even = work[j];",
          "  work[j] = kyber_add(butterfly_even, butterfly_product);",
          s"  work[j + $length] = kyber_sub(butterfly_even, butterfly_product);",
          "end"
        )
        start += 2 * length
      length /= 2
    result

  private def inverseBody: Vector[String] =
    var constantIndex = 127
    var result = Vector.empty[String]
    var length = 2
    while length <= 128 do
      var start = 0
      while start < 256 do
        val zeta = zetas(constantIndex)
        constantIndex -= 1
        result ++= Vector(
          s"for (j = $start; j < ${start + length}; j = j + 1) begin",
          "  butterfly_even = work[j];",
          s"  butterfly_odd = work[j + $length];",
          "  work[j] = kyber_add(butterfly_even, butterfly_odd);",
          s"  work[j + $length] = kyber_mul(kyber_sub(butterfly_odd, butterfly_even), 12'd$zeta);",
          "end"
        )
        start += 2 * length
      length *= 2
    result ++ Vector("for (j = 0; j < 256; j = j + 1) work[j] = kyber_mul(work[j], 12'd3303);")

  def emit(top: String = "KyberHPM1PE"): String =
    require(top.matches("[A-Za-z_][A-Za-z0-9_$]*"))
    s"""// Generated by NGen from the seven-layer Kyber incomplete NTT plan.
       |/* verilator lint_off BLKSEQ */
       |/* verilator lint_off UNUSEDSIGNAL */
       |/* verilator lint_off WIDTHEXPAND */
       |/* verilator lint_off WIDTHTRUNC */
       |module $top(
       |  input clk,
       |  input reset,
       |  input load_a_f,
       |  input load_a_i,
       |  input load_b_f,
       |  input load_b_i,
       |  input read_a,
       |  input read_b,
       |  input start_ab,
       |  input start_fntt,
       |  input start_pwm2,
       |  input start_intt,
       |  input [11:0] din,
       |  output reg [11:0] dout,
       |  output reg done
       |);
       |  localparam [12:0] KYBER_Q = 13'd3329;
       |  localparam [12:0] BARRETT_MU = 13'd5039;
       |  reg [11:0] bank_a [0:255];
       |  reg [11:0] bank_b [0:255];
       |  reg [11:0] work [0:255];
       |  reg [11:0] butterfly_product, butterfly_even, butterfly_odd;
       |  reg load_active, load_inverse, load_bank_b;
       |  reg read_active, read_inverse, read_bank_b, last_inverse;
       |  integer load_count, read_count, read_delay, busy_count, j, logical_index;
       |
       |  function automatic [11:0] kyber_add(input [11:0] a,input [11:0] b);
       |    reg [12:0] sum; begin sum={1'b0,a}+{1'b0,b}; if(sum>=KYBER_Q) sum=sum-KYBER_Q; kyber_add=sum[11:0]; end
       |  endfunction
       |  function automatic [11:0] kyber_sub(input [11:0] a,input [11:0] b);
       |    reg [12:0] value; begin if(a>=b) value=a-b; else value={1'b0,a}+KYBER_Q-b; kyber_sub=value[11:0]; end
       |  endfunction
       |  function automatic [11:0] kyber_mul(input [11:0] a,input [11:0] b);
       |    reg [23:0] product; reg [36:0] scaled; reg [12:0] quotient; reg [23:0] quotient_product; reg signed [24:0] remainder;
       |    begin product=a*b; scaled=product*BARRETT_MU; quotient=scaled[36:24]; quotient_product=quotient*KYBER_Q; remainder=$$signed({1'b0,product})-$$signed({1'b0,quotient_product}); if(remainder<0) remainder=remainder+KYBER_Q; if(remainder>=KYBER_Q) remainder=remainder-KYBER_Q; if(remainder>=KYBER_Q) remainder=remainder-KYBER_Q; kyber_mul=remainder[11:0]; end
       |  endfunction
       |
       |  task automatic compute_forward; begin
       |${lines(forwardBody,4)}
       |  end endtask
       |  task automatic compute_inverse; begin
       |${lines(inverseBody,4)}
       |  end endtask
       |
       |  always @(posedge clk) begin
       |    if(reset) begin
       |      dout<=0; done<=0; load_active<=0; read_active<=0; last_inverse<=0; load_count<=0; read_count<=0; read_delay<=0; busy_count<=0;
       |      for(j=0;j<256;j=j+1) begin bank_a[j]<=0; bank_b[j]<=0; work[j]<=0; end
       |    end else begin
       |      done<=0;
       |      if(load_a_f||load_a_i||load_b_f||load_b_i) begin load_active<=1; load_count<=0; load_inverse<=load_a_i||load_b_i; load_bank_b<=load_b_f||load_b_i; end
       |      else if(load_active) begin
       |        if(load_inverse) begin case(load_count[1:0]) 2'd0:logical_index=load_count; 2'd1:logical_index=load_count+1; 2'd2:logical_index=load_count-1; default:logical_index=load_count; endcase end else logical_index=load_count;
       |        if(load_bank_b) bank_b[logical_index]<=din; else bank_a[logical_index]<=din;
       |        if(load_count==255) begin load_active<=0; load_count<=0; end else load_count<=load_count+1;
       |      end
       |      if(start_fntt||start_intt) begin
       |        for(j=0;j<256;j=j+1) work[j]=start_ab?bank_b[j]:bank_a[j];
       |        if(start_intt) compute_inverse(); else compute_forward();
       |        for(j=0;j<256;j=j+1) if(start_ab) bank_b[j]<=work[j]; else bank_a[j]<=work[j];
       |        last_inverse<=start_intt; busy_count<=8;
       |      end else if(busy_count>0) begin busy_count<=busy_count-1; if(busy_count==1) done<=1; end
       |      if(read_a||read_b) begin read_active<=1; read_count<=0; read_delay<=2; read_bank_b<=read_b; read_inverse<=last_inverse; end
       |      else if(read_active) begin
       |        if(read_delay>0) begin read_delay<=read_delay-1; if(read_delay==1) begin logical_index=read_inverse?(read_count[0]?128+(read_count>>1):(read_count>>1)):((read_count>>2)*4+(read_count[1:0]==1?2:(read_count[1:0]==2?1:read_count[1:0]))); dout<=read_bank_b?bank_b[logical_index]:bank_a[logical_index]; end end
       |        else begin if(read_count==255) begin read_active<=0; read_count<=0; end else begin read_count<=read_count+1; logical_index=read_inverse?((read_count+1)&1?128+((read_count+1)>>1):((read_count+1)>>1)):(((read_count+1)>>2)*4+(((read_count+1)&3)==1?2:(((read_count+1)&3)==2?1:((read_count+1)&3)))); dout<=read_bank_b?bank_b[logical_index]:bank_a[logical_index]; end end
       |      end
       |    end
       |  end
       |endmodule
       |/* verilator lint_on WIDTHTRUNC */
       |/* verilator lint_on WIDTHEXPAND */
       |/* verilator lint_on UNUSEDSIGNAL */
       |/* verilator lint_on BLKSEQ */
       |""".stripMargin
