package ngen.backend

import ngen.algebra.Domains
import ngen.transform.KyberNtt
import ngen.rtl.{IndexedOperation, MicroProgram}

object KyberSystemVerilog:
  val ForwardCycles = 896
  val InverseCycles = 1152
  private val domain = Domains.Kyber256
  private val zetas = KyberNtt.zetas(domain).map(_.toInt)
  private def montgomeryConstant(value: Int): Int = ((BigInt(value) * (BigInt(1) << 16)) % 3329).toInt
  private def lines(values: Seq[String], spaces: Int): String = values.map(" " * spaces + _).mkString("\n")

  private final case class MicroOp(kind: Int, left: Int, right: Int, constant: Int) extends IndexedOperation:
    override val indices: Set[Int] = if kind == 3 then Set(left) else Set(left, right)

  private def forwardProgram: Vector[MicroOp] =
    var constantIndex = 1
    var result = Vector.empty[MicroOp]
    var length = 128
    while length >= 2 do
      var start = 0
      while start < 256 do
        val zeta = zetas(constantIndex)
        constantIndex += 1
        for index <- start until start + length do result :+= MicroOp(1, index, index + length, zeta)
        start += 2 * length
      length /= 2
    result

  private def inverseProgram: Vector[MicroOp] =
    var constantIndex = 127
    var result = Vector.empty[MicroOp]
    var length = 2
    while length <= 128 do
      var start = 0
      while start < 256 do
        val zeta = zetas(constantIndex)
        constantIndex -= 1
        for index <- start until start + length do result :+= MicroOp(2, index, index + length, zeta)
        start += 2 * length
      length *= 2
    result ++ Vector.tabulate(256)(index => MicroOp(3, index, index, 3303))

  def emit(top: String = "KyberHPM1PE"): String =
    require(top.matches("[A-Za-z_][A-Za-z0-9_$]*"))
    val forward = MicroProgram.schedule(forwardProgram, 1).bundles.flatten
    val inverse = MicroProgram.schedule(inverseProgram, 1).bundles.flatten
    val forwardRom = forward.zipWithIndex.map { case (op, index) =>
      s"f_kind[$index]=2'd${op.kind}; f_left[$index]=8'd${op.left}; f_right[$index]=8'd${op.right}; f_constant[$index]=12'd${montgomeryConstant(op.constant)};"
    }
    val inverseRom = inverse.zipWithIndex.map { case (op, index) =>
      s"i_kind[$index]=2'd${op.kind}; i_left[$index]=8'd${op.left}; i_right[$index]=8'd${op.right}; i_constant[$index]=12'd${montgomeryConstant(op.constant)};"
    }
    s"""// Generated by NGen from the seven-layer Kyber incomplete NTT plan.
       |/* verilator lint_off BLKSEQ */
       |/* verilator lint_off UNUSEDSIGNAL */
       |/* verilator lint_off WIDTHEXPAND */
       |/* verilator lint_off WIDTHTRUNC */
       |module $top(
       |  input clk,
       |  input reset,
       |  input load_a_f,
       |  input load_a_i,
       |  input load_b_f,
       |  input load_b_i,
       |  input read_a,
       |  input read_b,
       |  input start_ab,
       |  input start_fntt,
       |  input start_pwm2,
       |  input start_intt,
       |  input [11:0] din,
       |  output reg [11:0] dout,
       |  output reg done
       |);
       |  localparam [12:0] KYBER_Q = 13'd3329;
       |  localparam [15:0] KYBER_QINV = 16'd3327;
       |  reg [11:0] bank_a [0:255];
       |  reg [11:0] bank_b [0:255];
       |  reg [11:0] work [0:255];
       |  localparam integer FORWARD_LENGTH = ${forward.size};
       |  localparam integer INVERSE_LENGTH = ${inverse.size};
       |  reg [1:0] f_kind [0:FORWARD_LENGTH-1]; reg [7:0] f_left [0:FORWARD_LENGTH-1]; reg [7:0] f_right [0:FORWARD_LENGTH-1]; reg [11:0] f_constant [0:FORWARD_LENGTH-1];
       |  reg [1:0] i_kind [0:INVERSE_LENGTH-1]; reg [7:0] i_left [0:INVERSE_LENGTH-1]; reg [7:0] i_right [0:INVERSE_LENGTH-1]; reg [11:0] i_constant [0:INVERSE_LENGTH-1];
       |  reg load_active, load_inverse, load_bank_b;
       |  reg read_active, read_inverse, read_bank_b, last_inverse, executing, operation_inverse, operation_bank_b, finishing;
       |  integer load_count, read_count, read_delay, j, logical_index, pc;
       |
       |  function automatic [11:0] kyber_add(input [11:0] a,input [11:0] b);
       |    reg [12:0] sum; begin sum={1'b0,a}+{1'b0,b}; if(sum>=KYBER_Q) sum=sum-KYBER_Q; kyber_add=sum[11:0]; end
       |  endfunction
       |  function automatic [11:0] kyber_sub(input [11:0] a,input [11:0] b);
       |    reg [12:0] value; begin if(a>=b) value=a-b; else value={1'b0,a}+KYBER_Q-b; kyber_sub=value[11:0]; end
       |  endfunction
       |  function automatic [11:0] kyber_mul(input [11:0] a,input [11:0] b_montgomery);
       |    reg [23:0] product; reg [39:0] qinv_product; reg [15:0] correction; reg [28:0] sum; reg [12:0] reduced;
       |    begin product=a*b_montgomery; qinv_product=product*KYBER_QINV; correction=qinv_product[15:0]; sum={5'd0,product}+correction*KYBER_Q; reduced=sum[28:16]; if(reduced>=KYBER_Q) reduced=reduced-KYBER_Q; kyber_mul=reduced[11:0]; end
       |  endfunction
       |
       |  initial begin
       |${lines(forwardRom,4)}
       |${lines(inverseRom,4)}
       |  end
       |
       |  always @(posedge clk) begin
       |    if(reset) begin
       |      dout<=0; done<=0; load_active<=0; read_active<=0; last_inverse<=0; executing<=0; finishing<=0; pc<=0; load_count<=0; read_count<=0; read_delay<=0;
       |      for(j=0;j<256;j=j+1) begin bank_a[j]<=0; bank_b[j]<=0; work[j]<=0; end
       |    end else begin
       |      done<=0;
       |      if(load_a_f||load_a_i||load_b_f||load_b_i) begin load_active<=1; load_count<=0; load_inverse<=load_a_i||load_b_i; load_bank_b<=load_b_f||load_b_i; end
       |      else if(load_active) begin
       |        if(load_inverse) begin case(load_count[1:0]) 2'd0:logical_index=load_count; 2'd1:logical_index=load_count+1; 2'd2:logical_index=load_count-1; default:logical_index=load_count; endcase end else logical_index=load_count;
       |        if(load_bank_b) bank_b[logical_index]<=din; else bank_a[logical_index]<=din;
       |        if(load_count==255) begin load_active<=0; load_count<=0; end else load_count<=load_count+1;
       |      end
       |      if(start_fntt||start_intt) begin
       |        for(j=0;j<256;j=j+1) work[j]<=start_ab?bank_b[j]:bank_a[j];
       |        operation_inverse<=start_intt; operation_bank_b<=start_ab; last_inverse<=start_intt; pc<=0; executing<=1;
       |      end else if(executing) begin
       |        if(operation_inverse) begin
       |          case(i_kind[pc])
       |            2'd2: begin work[i_left[pc]]<=kyber_add(work[i_left[pc]],work[i_right[pc]]); work[i_right[pc]]<=kyber_mul(kyber_sub(work[i_right[pc]],work[i_left[pc]]),i_constant[pc]); end
       |            2'd3: work[i_left[pc]]<=kyber_mul(work[i_left[pc]],i_constant[pc]);
       |            default: begin end
       |          endcase
       |          if(pc==INVERSE_LENGTH-1) begin pc<=0; executing<=0; finishing<=1; end else pc<=pc+1;
       |        end else begin
       |          work[f_left[pc]]<=kyber_add(work[f_left[pc]],kyber_mul(work[f_right[pc]],f_constant[pc]));
       |          work[f_right[pc]]<=kyber_sub(work[f_left[pc]],kyber_mul(work[f_right[pc]],f_constant[pc]));
       |          if(pc==FORWARD_LENGTH-1) begin pc<=0; executing<=0; finishing<=1; end else pc<=pc+1;
       |        end
       |      end else if(finishing) begin for(j=0;j<256;j=j+1) if(operation_bank_b) bank_b[j]<=work[j]; else bank_a[j]<=work[j]; finishing<=0; done<=1; end
       |      if(read_a||read_b) begin read_active<=1; read_count<=0; read_delay<=2; read_bank_b<=read_b; read_inverse<=last_inverse; end
       |      else if(read_active) begin
       |        if(read_delay>0) begin read_delay<=read_delay-1; if(read_delay==1) begin logical_index=read_inverse?(read_count[0]?128+(read_count>>1):(read_count>>1)):((read_count>>2)*4+(read_count[1:0]==1?2:(read_count[1:0]==2?1:read_count[1:0]))); dout<=read_bank_b?bank_b[logical_index]:bank_a[logical_index]; end end
       |        else begin if(read_count==255) begin read_active<=0; read_count<=0; end else begin read_count<=read_count+1; logical_index=read_inverse?((read_count+1)&1?128+((read_count+1)>>1):((read_count+1)>>1)):(((read_count+1)>>2)*4+(((read_count+1)&3)==1?2:(((read_count+1)&3)==2?1:((read_count+1)&3)))); dout<=read_bank_b?bank_b[logical_index]:bank_a[logical_index]; end end
       |      end
       |    end
       |  end
       |endmodule
       |/* verilator lint_on WIDTHTRUNC */
       |/* verilator lint_on WIDTHEXPAND */
       |/* verilator lint_on UNUSEDSIGNAL */
       |/* verilator lint_on BLKSEQ */
       |""".stripMargin
