package ngen.backend

import ngen.rtl.SwitchTransposeSpec

object SwitchTransposeSystemVerilog:
  private def unit(bits: Int, dataWidth: Int): String =
    val width = 1 << bits
    val half = width / 2
    def upper(lane: Int, stage: Int) = s"upper_${lane}_$stage"
    def lower(lane: Int, stage: Int) = s"lower_${lane}_$stage"
    val registers = (for lane <- 0 until half; stage <- 0 until half yield
      s"reg [${dataWidth - 1}:0] ${upper(lane,stage)}; reg [${dataWidth - 1}:0] ${lower(lane,stage)};"
    ).mkString("\n  ")
    val outputs = (0 until half).flatMap { lane => Vector(
      s"assign data_out[${lane * dataWidth} +: $dataWidth] = ${lower(lane,half-1)};",
      s"assign data_out[${(lane + half) * dataWidth} +: $dataWidth] = select ? data_in[${lane * dataWidth} +: $dataWidth] : ${upper(lane,half-1)};"
    )}.mkString("\n  ")
    val resetPipes = (for lane <- 0 until half; stage <- 0 until half yield
      s"${upper(lane,stage)} <= '0; ${lower(lane,stage)} <= '0;"
    ).mkString("\n      ")
    val shiftPipes = (0 until half).flatMap { lane =>
      Vector(
        s"${upper(lane,0)} <= data_in[${(lane + half) * dataWidth} +: $dataWidth];",
        s"${lower(lane,0)} <= select ? ${upper(lane,half-1)} : data_in[${lane * dataWidth} +: $dataWidth];"
      ) ++ (1 until half).flatMap(stage => Vector(
        s"${upper(lane,stage)} <= ${upper(lane,stage-1)};",
        s"${lower(lane,stage)} <= ${lower(lane,stage-1)};"
      ))
    }.mkString("\n      ")
    val control =
      if bits == 1 then
        """valid_out <= valid_in;
          |      if (valid_in) select <= ~select;
          |      else select <= 1'b0;""".stripMargin
      else
        s"""case (state)
           |        2'd0: if (valid_in) begin state <= 2'd1; count <= count + 1'b1; end
           |        2'd1: begin count <= count + 1'b1; if (count == ${half - 1}) begin select <= ~select; count <= 0; valid_out <= 1'b1; state <= 2'd2; end end
           |        2'd2: begin count <= count + 1'b1; if (count == ${half - 1}) begin select <= ~select; count <= 0; if ((~select) && (~valid_in)) begin valid_out <= 1'b0; select <= 1'b0; state <= 2'd0; end end end
           |        default: begin state <= 2'd0; valid_out <= 1'b0; select <= 1'b0; count <= 0; end
           |      endcase""".stripMargin
    s"""module NGenSwitchTransposeUnit_$bits(
       |  input clock, input reset, input valid_in,
       |  input [${width * dataWidth - 1}:0] data_in,
       |  output valid_out, output [${width * dataWidth - 1}:0] data_out
       |);
       |  reg valid_reg, select; reg [1:0] state; integer count;
       |  assign valid_out = valid_reg;
       |  $registers
       |  $outputs
       |  always @(posedge clock) begin
       |    if (reset) begin valid_reg <= 1'b0; select <= 1'b0; state <= 0; count <= 0;
       |      $resetPipes
       |    end else begin
       |      $shiftPipes
       |      $control
       |    end
       |  end
       |endmodule
       |""".stripMargin.replace("valid_out <=", "valid_reg <=")

  private def network(bits: Int, dataWidth: Int): String =
    val width = 1 << bits
    if bits == 1 then
      s"""module NGenSwitchTransposeNetwork_1(input clock,input reset,input valid_in,input [${2 * dataWidth - 1}:0] data_in,output valid_out,output [${2 * dataWidth - 1}:0] data_out);
         |  NGenSwitchTransposeUnit_1 unit(clock,reset,valid_in,data_in,valid_out,data_out);
         |endmodule
         |""".stripMargin

    else
      val halfBits = width * dataWidth / 2
      s"""module NGenSwitchTransposeNetwork_$bits(input clock,input reset,input valid_in,input [${width * dataWidth - 1}:0] data_in,output valid_out,output [${width * dataWidth - 1}:0] data_out);
         |  wire unit_valid; wire [${width * dataWidth - 1}:0] unit_data; wire lower_valid, upper_valid;
         |  NGenSwitchTransposeUnit_$bits unit(clock,reset,valid_in,data_in,unit_valid,unit_data);
         |  NGenSwitchTransposeNetwork_${bits-1} lower(clock,reset,unit_valid,unit_data[0 +: $halfBits],lower_valid,data_out[0 +: $halfBits]);
         |  NGenSwitchTransposeNetwork_${bits-1} upper(clock,reset,unit_valid,unit_data[$halfBits +: $halfBits],upper_valid,data_out[$halfBits +: $halfBits]);
         |  assign valid_out = lower_valid;
         |endmodule
         |""".stripMargin

  def definitions(spec: SwitchTransposeSpec): String =
    (1 to spec.logSize).map(bits => unit(bits,spec.dataWidth) + network(bits,spec.dataWidth)).mkString("\n")

  def emit(spec: SwitchTransposeSpec, top: String = "SwitchTransposeTop"): String =
    require(top.matches("[A-Za-z_][A-Za-z0-9_$]*"), s"invalid module name: $top")
    val dependencies = definitions(spec)
    s"""// Generated by NGen from the HOGE SwitchTransposeUnit architecture.
       |$dependencies
       |module $top(input clock,input reset,input valid_in,input [${spec.size * spec.dataWidth - 1}:0] data_in,output valid_out,output [${spec.size * spec.dataWidth - 1}:0] data_out);
       |  NGenSwitchTransposeNetwork_${spec.logSize} network(clock,reset,valid_in,data_in,valid_out,data_out);
       |endmodule
       |""".stripMargin
